name: Docker CD

on:
  push:
    branches:
      - "master"
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: startsWith(github.ref, 'refs/heads/master')
        run: echo "TAG=latest" >> $GITHUB_ENV

      - if: startsWith(github.ref, 'refs/tags')
        run: |
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          no-cache: true
          tags: |
            ghcr.io/zekrotja/stargrab:${{ env.TAG }}